databases:
  - name: renderdeploy
    databaseName: renderdeploy
    user: renderdeploy

services:
  - type: web
    name: renderdeploy
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: renderdeploy
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
